### ISSUE TITLE
"in" keyword not supported

### ISSUE THREAD

**Issue by jozefferko** [brianneisler/firemin#30]
attempting to minimize rules containing a comma throws an error.

<img width="481" alt="Screenshot 2021-02-13 at 20 14 50" src="https://user-images.githubusercontent.com/20824772/107859220-3ddc3e00-6e38-11eb-8426-f78ff431c91e.png">

<img width="1205" alt="Screenshot 2021-02-13 at 20 13 27" src="https://user-images.githubusercontent.com/20824772/107859173-f190fe00-6e37-11eb-9757-5e0b43e6570b.png">

**Comment by brianneisler** [comment]
Hmm, I think this may be related to the “in” keyword. Thanks for reporting! I’ll take a look at the issue and get back to you.

**Comment by brianneisler** [comment]
Yep, currently parser is not handling the in keyword so it thinks it's an identifier and that the array brackets are a property accessor.

I'll take a stab at adding support for the "in" keyword this weekend.

**Comment by brianneisler** [comment]
@jozefferko sorry for the delay in fixing this. Ended up being wrapped into a refactor that took a while to complete. Support for the "in" keyword has been added in the v0.2.2 release https://github.com/brianneisler/firemin/pull/32
